package einkaufVerwalter.gui;

import einkaufVerwalter.data.Einkauf;
import einkaufVerwalter.model.EinkaufModel;


public class EinkaufVerwalterGUI extends javax.swing.JFrame {
    private final EinkaufModel MODEL;
    
    /** Creates new form GUI */
    public EinkaufVerwalterGUI() {
        initComponents();
        this.MODEL = new EinkaufModel();
        this.tArtikel.setModel(MODEL);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tArtikel = new javax.swing.JTable();
        mbMenu = new javax.swing.JMenuBar();
        meEinkauf = new javax.swing.JMenu();
        miAdd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Einkauf Verwalter");

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Artikel"));

        tArtikel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tArtikel);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        meEinkauf.setText("Einkauf");

        miAdd.setText("Add");
        miAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAdd(evt);
            }
        });
        meEinkauf.add(miAdd);

        mbMenu.add(meEinkauf);

        setJMenuBar(mbMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAdd
        this.MODEL.add(new Einkauf());
    }//GEN-LAST:event_onAdd

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EinkaufVerwalterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenu meEinkauf;
    private javax.swing.JMenuItem miAdd;
    private javax.swing.JTable tArtikel;
    // End of variables declaration//GEN-END:variables

}
